export const typeClasses = {
  cardBackground: {
    grass: 'type-grass',
    fire: 'type-fire',
    water: 'type-water',
    electric: 'type-electric',
    normal: 'type-normal',
    flying: 'type-flying',
    fighting: 'type-fighting',
    poison: 'type-poison',
    ground: 'type-ground',
    rock: 'type-rock',
    psychic: 'type-psychic',
    ice: 'type-ice',
    bug: 'type-bug',
    ghost: 'type-ghost',
    steel: 'type-steel',
    dragon: 'type-dragon',
    dark: 'type-dark',
    fairy: 'type-fairy'
  },
  badgeBackground: {
    grass: 'badge-grass',
    fire: 'badge-fire',
    water: 'badge-water',
    electric: 'badge-electric',
    normal: 'badge-normal',
    flying: 'badge-flying',
    fighting: 'badge-fighting',
    poison: 'badge-poison',
    ground: 'badge-ground',
    rock: 'badge-rock',
    psychic: 'badge-psychic',
    ice: 'badge-ice',
    bug: 'badge-bug',
    ghost: 'badge-ghost',
    steel: 'badge-steel',
    dragon: 'badge-dragon',
    dark: 'badge-dark',
    fairy: 'badge-fairy'
  }
}